### ISSUE TITLE
ReferenceAssemblyAttribute missing

### ISSUE THREAD

**Issue by miloush** [JetBrains/Refasmer#6]
According to the [documentation](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies#reference-assemblies-structure), reference assemblies should contain [`ReferenceAssembly`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.referenceassemblyattribute?view=net-5.0) attribute, but it doesn't seem to be injected by refasmer.

**Comment by bneumann** [comment]
I also found that. I used dnspy to add it afterwards.

**Comment by hypersw** [comment]
The original goal for Refasmer were to make an assembly which has the same public API as the original assembly, but no implementation details (i.e. identical to the original assembly from the compiler point of view). This way the stripped-down assembly could be fed into the compiler and skip compilation if only insignificant implementation details changed inside. Adding new attributes would have contradicted this purpose, obviously.

But it's a reasonable request to support an option to whether add this attribute or not, of course.

**Comment by jnm2** [comment]
There's a lot of experience around such an assembly already, such as what implementation details can and can't be removed without observable side effects when compiling using the assembly as a reference.

https://github.com/dotnet/roslyn/blob/main/docs/features/refout.md
https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies

As described in the documents above, ReferenceAssemblyAttribute prevents the assembly from being loaded by the runtime.

**Comment by hypersw** [comment]
This has been tested against our full codebase, including funny cases like when you remove private classes and this makes a namespace nonexistent and makes compilation fail because now an unused `using` becomes invalid. I know these or similar docs were considered too.
There's even a parameter named `filter` which controls what is kept and what is dropped when stripping assemblies, to vary behavior between what's closer to the docs and what best fits what we needed (the minima set sufficient for the compiler, to have it change as rarely as possible to hit the compilation caches).

Funny thing that they'd mention PEVerify, it's a rather strange tool which misses some things runtime would crash on but errs on many a valid CIL. Once upon a time I tried to use it for checking emitted IL and it were not too relevant for any real use. Catching simple stack unbalancing maybe.

**Comment by zabbius** [comment]
I've implemented [ReferenceAssembly] support. Will make release after some testing.

**Comment by zabbius** [comment]
Done in 1.0.17
